config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :topics do
    resources :posts do
      resources :comments
    end
  end

  get 'rights' => 'rights#show', as: "rights"
  post 'rights/update_rights' => 'rights#update_rights', as: "update_rights"

  get 'topics/:id/manage_users' => 'topics#manage_users', as: "manage_users"
  post 'topics/:id/manage_users/invite' => 'topics#invite_user', as: "invite_user"
  post 'topics/:id/manage_users/invite_all' => 'topics#invite_all_filtered_users', as: "invite_all_filtered_users"
  post 'topics/:id/manage_users/disinvite' => 'topics#disinvite_user', as: "disinvite_user"
  post 'topics/:id/leave_topic' => 'topics#leave_topic', as: "leave_topic"

  root 'topics#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates_presence_of :content, message:'Es muss Text im Beitrag enthalten sein.'
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_parents
	before_action :find_comment, only: [:edit, :update, :destroy]

	def create
		@comment = @post.comments.create(comment_params)
		@comment.user_id = current_user.id
		if @comment.save
			redirect_to topic_path(@topic)
		else
			redirect_to topic_path(@topic), alert: "Keine leeren Kommentare möglich!"		
		end
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to topic_path(@topic)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to topic_path(@topic)
	end

	private

		def comment_params
			params.require(:comment).permit(:content, :linkUrl, :linkText)
		end

		def find_comment
			@comment = @post.comments.find(params[:id])
		end

		def find_parents
			@post = Post.find(params[:post_id])
			@topic = Topic.find(@post.topic_id)
		end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% post = Post.find(comment.post_id) %>
<div class="comment">
	<% unless comment.linkUrl == "" %>
		<a href="<%= comment.linkUrl %>" target="_blank" title="<%= comment.linkText %>" class="content-link"> <%= comment.linkText %> </a>
	<% end %>
	<p class="comment-content"><%= comment.content.gsub(/\n/, '<br/>').html_safe %></p>
	<p class="comment-posted-by"><%= signature_string(comment.user.username, comment.created_at, comment.updated_at) %></p>

	<div class="links">
		<% if comment.user_id == current_user.id %>
			<%= link_to edit_topic_post_comment_path(post.topic, post, comment), class: "btn btn-default", title: "Bearbeiten" do %>
				<span class="glyphicon glyphicon-pencil"></span>
			<% end %>
		<% end %>
		<% if comment.user_id == current_user.id || current_user.rights == 2 %>
			<%= link_to topic_post_comment_path(post.topic, post, comment), class: "btn btn-default", method: :delete, title: "Thema löschen", data: { confirm: "Möchten Sie das Thema wirklich löschen?" } do %>
				<span class="glyphicon glyphicon-remove"></span>
			<% end %>
		<% end %>
	</div>
</div>

app/views/comments/_form.html.erb
<% new_id = "new-comment-#{@post.id}" %>
<%= simple_form_for([@topic, @post, @post.comments.build]) do |f| %> 
	<%= f.input :content, label: "Kommentar", input_html: { id: new_id } %>
	<%= f.input :linkUrl, input_html: { id: new_id + "-lurl" }, as: :hidden %>
	<%= f.input :linkText, input_html: { id: new_id + "-ltext" },as: :hidden %>
	<div class="text_icons">
		<%= render 'layouts/text_decoration', id: new_id %>
	</div>
	<%= f.button :submit, :class => 'btn btn-default', :value => "Kommentieren" %>
<% end %>

app/views/comments/edit.html.erb
<% new_id = "edit-comment-#{@post.id}" %>
<h2 class="hCenter">Kommentar bearbeiten</h2>

<div class="edit_topic">
	<%= simple_form_for([@topic, @post, @comment]) do |f| %>
		<%= f.input :content, label: "Kommentar", input_html: { id: new_id } %>
		<%= f.input :linkUrl, input_html: { id: new_id + "-lurl" } %>
		<%= f.input :linkText, input_html: { id: new_id + "-ltext" } %>
		<%= f.button :submit, value: "Speichern", class: "btn-special" %>
		<%= link_to "Abbrechen", topic_path(@topic), class: "btn btn-default btn-special" %>
	<% end %>
</div>