config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :topics do
    resources :posts do
      resources :comments
    end
  end

  get 'rights' => 'rights#show', as: "rights"
  post 'rights/update_rights' => 'rights#update_rights', as: "update_rights"

  get 'topics/:id/manage_users' => 'topics#manage_users', as: "manage_users"
  post 'topics/:id/manage_users/invite' => 'topics#invite_user', as: "invite_user"
  post 'topics/:id/manage_users/invite_all' => 'topics#invite_all_filtered_users', as: "invite_all_filtered_users"
  post 'topics/:id/manage_users/disinvite' => 'topics#disinvite_user', as: "disinvite_user"
  post 'topics/:id/leave_topic' => 'topics#leave_topic', as: "leave_topic"

  root 'topics#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :user
	has_many :posts
	has_and_belongs_to_many :users
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	before_action :find_topic, only: [:show, :edit, :update, :destroy, :manage_users, :invite_user, :invite_all_filtered_users, :disinvite_user, :leave_topic]
	before_action :find_posts, only: [:show]
	before_action :authenticate_user!

	def index
		@own_topics  = Topic.where(user_id: current_user.id).order("created_at DESC")
		if current_user.rights == 2
			related_topics = Topic.all
		else
			related_topics = current_user.topics
		end
		@related_topics = related_topics.select { |topic| !@own_topics.include?(topic) }
	end

	def show
		unless current_user == @topic.user || current_user.rights == 2 || @topic.users.include?(current_user)
			redirect_to topics_path
		end
		visit = Visit.where(:user_id => current_user.id, :topic_id => @topic.id).take
		if visit == nil
			visit = Visit.create(:visited_at => Time.now, :user_id => current_user.id, :topic_id => @topic.id)
		else
			visit.visited_at = Time.now
		end
		visit.save
	end

	def new
		@topic = current_user.topics.build
	end

	def create
		@topic = current_user.topics.build(topic_params)
		@topic.user_id = current_user.id
		
		if @topic.save
			redirect_to topics_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @topic.update(topic_params)
			redirect_to topic_path
		else
			render 'edit'
		end
		
	end

	def destroy
		@topic.destroy
		redirect_to topics_path
	end

	def manage_users
		@related_users = @topic.users.order('username')
		searched_users = User.search(params[:search]).order('username')
		@filtered_users = searched_users.select { |user| !@related_users.include?(user) && user.id != @topic.user_id}
	end

	def invite_user
		user = User.find(params[:user_id])
		@topic.users << user unless @topic.users.include?(user)
		save_users_and_redirect(@topic)
	end

	def invite_all_filtered_users
		params[:filtered_users].each do |user_id|
			user = User.find(user_id)
			@topic.users << user unless @topic.users.include?(user)
		end
		save_users_and_redirect(@topic)
	end

	def disinvite_user
		user = User.find(params[:user_id])
		@topic.users.delete(user)
		save_users_and_redirect(@topic)
	end

	def leave_topic
		@topic.users.delete(current_user)
		if @topic.save
			redirect_to topics_path
		else
			render 'show'
		end
	end

	private

		def topic_params
			params.require(:topic).permit(:title, :description)
		end

		def find_topic
			@topic = Topic.find(params[:id])
		end

		def find_posts
			@posts = Post.where("topic_id = ?", params[:id])
		end

		def save_users_and_redirect(topic)
			if topic.save
				redirect_to manage_users_path
			else
				render 'manage_users'
			end
		end

end

app/helpers/topics_helper.rb
module TopicsHelper

	def count_new_posts_and_comments(topic)
		numberOfNewPostsAndComments = 0
		visit = Visit.where("topic_id = ? AND user_id =?", topic.id, current_user.id).take
		if visit == nil
			topic.posts.each do |post|
				numberOfNewPostsAndComments += (1 + post.comments.count) 
			end
		else
			visited_at = visit.visited_at
			topic.posts.each do |post|
				if visited_at < post.created_at
					numberOfNewPostsAndComments += 1
				end
				post.comments.each do |comment|
					if visited_at < comment.created_at
						numberOfNewPostsAndComments += 1
					end
				end
			end
		end
		return numberOfNewPostsAndComments
	end

end

app/views/topics/_form.html.erb
<%= simple_form_for @topic do |f| %>
	<%= f.input :title, label: "Thema" %>
	<%= f.input :description, label: "Beschreibung" %>
	<%= f.button :submit, class: "btn-special btn-bottom", value: "Speichern" %>
	<%= button_to "Abbrechen", :back, class: "btn btn-default btn-special" %>
<% end %>

app/views/topics/edit.html.erb
<h2 class="hCenter">Thema bearbeiten</h2>

<%= render 'form' %>

app/views/topics/index.html.erb
<% unless @own_topics.empty? %>
	<section class="container">
		<h1>Erstellte Themen</h1>
		<% @own_topics.each do |topic| %>
			<div class="col-md-4">
				<%= link_to topic_path(topic) do %>
					<div class="topic">
						<p class="topic-author"><%= topic.user.username %></p>
						<h2 class="topic-title"><%= topic.title %></h2>
						<% if count_new_posts_and_comments(topic) == 1 %>
						<p class="topic-author"><%= count_new_posts_and_comments(topic) %> neuer Beitrag</p>
						<% else %>
						<p class="topic-author"><%= count_new_posts_and_comments(topic) %> neue Beiträge</p>
						<% end %>
					</div>
				<% end %>
			</div>
		<% end %>
	</section>
<% end %>

<% unless @related_topics.empty? %>
	<section class="container">
		<h1>Themen</h1>
		<% @related_topics.each do |topic| %>
			<div class="col-md-4">
				<%= link_to topic_path(topic) do %>
					<div class="topic">
						<p class="topic-author"><%= topic.user.username %></p>
						<h2 class="topic-title"><%= topic.title %></h2>
						<% if count_new_posts_and_comments(topic) == 1 %>
						<p class="topic-author"><%= count_new_posts_and_comments(topic) %> neuer Beitrag</p>
						<% else %>
						<p class="topic-author"><%= count_new_posts_and_comments(topic) %> neue Beiträge</p>
						<% end %>
					</div>
				<%end%>
			</div>
		<% end %>
	</section>
<% end %>

<% if @own_topics.empty? && @related_topics.empty? %>
	<section class="container">
		<h1>Themen</h1>
		<i id="no_topic_yet">Du bist noch nicht zu einem Thema eingeladen. <br/> Sobald dich ein Autor zu einem Thema hinzugefügt hat, siehst du hier deine Themen.</i>
	</section>
<% end %>

app/views/topics/manage_users.html.erb
<div class="container manage_users">
	<div class="headline">
		<%= link_to topic_path, class: "btn btn-default" do %>
			<span class="glyphicon glyphicon-arrow-left"></span>
		<% end %>
		<h2 class="center"><%= @topic.title %></h2>
	</div>

	<div class="active_users">
		<h3 class="center">Aktive Benutzer</h3>
		<table>
		<% @related_users.each do |user| %>
			<tr>
				<td><p><%= user.username %><% if user.expertise != "" %> <i>(<%= user.expertise %>)</i><% end %></p></td>
				<td  class="right"><%= link_to "Entfernen", disinvite_user_path(user_id: user.id), method: :post, class: "btn btn-default" %></td>
			</tr>
		<% end %>
		</table>
		<% if @related_users.empty? %>
			<i class="center">Keine Benutzer hinzugefügt</i>
		<% end %>
	</div>
	
	<div class="invite_users">
		<h3 class="center">Benutzer einladen</h3>
		
				<%= form_tag("manage_users", method: :get, id: "search-form") do %>
						<%= text_field_tag :search, params[:search], placeholder: "Thema/Username/Email" %>
						<%= button_tag(type: "submit", class: "btn btn-default") do%>
							<span class="glyphicon glyphicon-search"></span>
						<% end %>
				<% end %>

				<% if !@filtered_users.empty? %>
				<%= link_to "Alle einladen", invite_all_filtered_users_path(filtered_users: @filtered_users), method: :post, class: "btn btn-default" %>
				<% else %>
					<i class="center" id="no_user">Kein passender Benutzer gefunden</i>
				<% end %>

		<table>	
				<% @filtered_users.each do |user| %>
					<tr>
						<td><p><%= user.username %><% if user.expertise != "" %> <i>(<%= user.expertise %>)</i><% end %></p></td>
						<td class="right"><%= link_to "Einladen", invite_user_path(user_id: user.id), method: :post, class: "btn btn-default" %></td>
					</tr>
				<% end %>
			
		</table>
	</div>
</div>

app/views/topics/new.html.erb
<div class="col-md-8 col-md-offset-2 new_topic">
	<h1>Neues Thema</h1>

	<%= render 'form' %>

	<%= link_to "Verwerfen", topics_path, class: "btn btn-default btn-special btn-bottom" %>
</div>

app/views/topics/show.html.erb
<div class="container chat">
	<div class="topic-show-head" onclick="show('topic-description')">

		<div id="icons">
			<div id="icons_left">
				<!-- Zurück -->
				<%= link_to topics_path, class: "btn btn-default", title: "Zurück" do %>
					<span class="glyphicon glyphicon-arrow-left"></span>
				<% end %>

				<!-- Neuer Post -->
				<a href="#add_new_post" class="btn btn-default no_display" title="Beitrag hinzufügen">
					<span class="glyphicon glyphicon-plus"></span>
				</a>

				<!-- Zurück -->
				<%= link_to topics_path, class: "btn btn-default no_display" do %>
					<span class="glyphicon glyphicon-arrow-left"></span>
				<% end %>

				<%= link_to topics_path, class: "btn btn-default no_display" do %>
					<span class="glyphicon glyphicon-arrow-left"></span>
				<% end %>
			</div>

			<div id="icons_right">
				<!-- Thema verlassen -->

				<!-- Benutzer verwalten -->
				<% if current_user.rights == 2 || @topic.user_id == current_user.id %>
					<a href="#add_new_post" class="btn btn-default" title="Beitrag hinzufügen">
						<span class="glyphicon glyphicon-plus"></span>
					</a>

					<%= link_to manage_users_path, class: "btn btn-default", title: "Benutzer verwalten" do %>
						<span class="glyphicon glyphicon-cog"></span>
					<% end %>

				<!-- Bearbeiten -->
				
					<%= link_to edit_topic_path(@topic), class: "btn btn-default", title: "Bearbeiten" do %>
						<span class="glyphicon glyphicon-pencil"></span>
					<% end %>

				<!-- Löschen -->
					<%= link_to topic_path(@topic), class: "btn btn-default", method: :delete, title: "Thema löschen", data: { confirm: "Möchten Sie das Thema wirklich löschen?" } do %>
						<span class="glyphicon glyphicon-remove"></span>
					<% end %>

					<% else %>
						<%= link_to manage_users_path, class: "btn btn-default no_display" do %>
						<span class="glyphicon glyphicon-cog"></span>
					<% end %>

				<!-- Bearbeiten -->
				
					<%= link_to edit_topic_path(@topic), class: "btn btn-default no_display" do %>
						<span class="glyphicon glyphicon-pencil"></span>
					<% end %>

					<a href="#add_new_post" class="btn btn-default" title="Beitrag hinzufügen">
						<span class="glyphicon glyphicon-plus"></span>
					</a>

				<!-- Löschen -->
					<% if @topic.users.include?(current_user) %>
						<%= link_to leave_topic_path, method: :post, class: "btn btn-default", title: "Thema verlassen", data: { confirm: "Möchten Sie das Thema wirklich unwiderruflich verlassen?" } do%>
							<span class="glyphicon glyphicon-log-out"></span>
						<% end %>
					<% end %>
				<% end %>
			</div>

			<p class="topic-posted-by"><%= @topic.user.username %></p>

		</div>

		
		<h2 class="topic-show-title">
			<%= @topic.title %>
		</h2>		
		<p class="topic-posted-at"><%= time_string(@topic.created_at) %></p>
		<div class="topic-desc" id="topic-description">
			<p><%= @topic.description.gsub(/\n/, '<br/>').html_safe %></p>
		</div>
	</div>

	<div class="topic-desc" id="topic-description">
		<p><%= @topic.description.gsub(/\n/, '<br/>').html_safe %></p>
		<% if current_user.rights == 2 || current_user.id == @topic.user_id %>
			<%= link_to "Bearbeiten", edit_topic_path(@topic), class: "btn btn-default" %>
			<%= link_to "Benutzer verwalten", manage_users_path, class: "btn btn-default" %>
			<%= link_to "Löschen", topic_path(@topic), class: "btn btn-default", method: :delete, data: { confirm: "Möchten Sie das Thema wirklich löschen?" } %>
		<% end %>
	</div>

	<div class="topic-show">
		<div id="posts">
			<% @posts.each do |post| %>
			<div class="onePost">
				<%= render post %>

				<div class = "comments" id="<%=post.id%>">

					<% if post.comments.count == 1%>
					<h4 id="<%=post.id%>" onclick="showComments('all_comments', this.id)"> <%=post.comments.count %> Kommentar </h4>
					<% else %>
					<h4 id="<%=post.id%>" onclick="showComments('all_comments', this.id)"> <%=post.comments.count %> Kommentare </h4>
					<% end %>
					
					<div class="all_comments">
						<%= render post.comments %>

						<% @post = post %>
						<%= render 'comments/form' %>
					</div>
				</div>

			</div>
			<% end %>
		</div>

		<div id="add_new_post" class="reply-to-msg" >
			<h3>Beitrag hinzufügen:</h3>
			<%= render 'posts/form' %>
		</div>
	</div>
</div>