config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :topics do
    resources :posts do
      resources :comments
    end
  end

  get 'rights' => 'rights#show', as: "rights"
  post 'rights/update_rights' => 'rights#update_rights', as: "update_rights"

  get 'topics/:id/manage_users' => 'topics#manage_users', as: "manage_users"
  post 'topics/:id/manage_users/invite' => 'topics#invite_user', as: "invite_user"
  post 'topics/:id/manage_users/invite_all' => 'topics#invite_all_filtered_users', as: "invite_all_filtered_users"
  post 'topics/:id/manage_users/disinvite' => 'topics#disinvite_user', as: "disinvite_user"
  post 'topics/:id/leave_topic' => 'topics#leave_topic', as: "leave_topic"

  root 'topics#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments

  validates_presence_of :content, message:'Es muss Text im Beitrag enthalten sein.'
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	respond_to :html, :json
	before_action :find_topic
	before_action :find_post, only: [:edit, :update, :destroy]

	def show
	end

	def create
		@post = @topic.posts.create(post_params)
		@post.user_id = current_user.id
		if @post.save
			redirect_to topic_path(@topic)
		else
			redirect_to topic_path(@topic), alert: "Keine leeren Beiträge möglich!"		
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to topic_path(@topic)
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to topic_path(@topic)
	end

	private

		def post_params
			params.require(:post).permit(:content, :linkUrl, :linkText, :imageUrl)
		end

		def find_topic
			@topic = Topic.find(params[:topic_id])
		end 

		def find_post
			@post = @topic.posts.find(params[:id])
		end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% new_id = "new-post-#{@topic.id}" %>
<%= simple_form_for([@topic, @topic.posts.build]) do |f| %> 
	
	<%= f.input :linkUrl, input_html: { id: new_id + "-lurl" }, as: :hidden %>
	<%= f.input :linkText, input_html: { id: new_id + "-ltext" }, as: :hidden %>
	<%= f.input :imageUrl, input_html: { id: new_id + "-iurl" }, as: :hidden %>
	<%= f.input :content, label: "Beitrag", input_html: { id: new_id } %>
	<div class="text_icons">
		<span onClick="appendImage('<%= new_id %>')" class="glyphicon glyphicon-picture glyphicon-form" title="Bild anhägen"></span>
		<%= render 'layouts/text_decoration', id: new_id %>
	</div>
	<%= f.button :submit, label: "Beitrag absenden", :class => 'btn-default', :value => "Beitrag absenden" %>

<% end %>

app/views/posts/_post.html.erb
<div class="post">
	<% unless post.imageUrl == "" %>
		<img src="<%= post.imageUrl %>" class="postImage"/>
	<% end %>
	<% unless post.linkUrl == "" %>
		<a href="<%= post.linkUrl %>" target="_blank" title="<%= post.linkText %>" class="content-link"> <%= post.linkText %> </a>
	<% end %>
	<p class="post-content"><%= post.content.gsub(/\n/, '<br/>').html_safe %></p>
	<p class="post-posted-by"> <%= signature_string(post.user.username, post.created_at, post.updated_at) %></p>

	<div class="links">
		<% if post.user_id == current_user.id %>
			<%= link_to edit_topic_post_path(post.topic, post), class: "btn btn-default", title: "Bearbeiten" do %>
						<span class="glyphicon glyphicon-pencil"></span>
					<% end %>
		<% end %>
		<% if post.user_id == current_user.id || current_user.rights == 2 %>
			<%= link_to topic_post_path(post.topic, post), class: "btn btn-default", method: :delete, title: "Thema löschen", data: { confirm: "Möchten Sie das Thema wirklich löschen?" } do %>
				<span class="glyphicon glyphicon-remove"></span>
			<% end %>
		<% end %>
	</div>

</div>

app/views/posts/edit.html.erb
<% new_id = "edit-comment-#{@topic.id}" %>
<h2 class="hCenter">Beitrag bearbeiten</h2>
<%= simple_form_for([@topic, @post]) do |f| %>
	<%= f.input :content, label: "Beitrag", input_html: { id: new_id } %>
	<%= f.input :linkUrl, input_html: { id: new_id + "-lurl" } %>
	<%= f.input :linkText, input_html: { id: new_id + "-ltext" } %>
	<%= f.input :imageUrl, input_html: { id: new_id + "-iurl" } %>
	<div class="links_right">
		<%= f.button :submit, value: "Speichern", class: "btn-special" %>
		<%= link_to "Abbrechen", topic_path(@topic), class: "btn btn-default btn-special" %>
	</div>
<% end %>