config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :topics do
    resources :posts do
      resources :comments
    end
  end

  get 'rights' => 'rights#show', as: "rights"
  post 'rights/update_rights' => 'rights#update_rights', as: "update_rights"

  get 'topics/:id/manage_users' => 'topics#manage_users', as: "manage_users"
  post 'topics/:id/manage_users/invite' => 'topics#invite_user', as: "invite_user"
  post 'topics/:id/manage_users/invite_all' => 'topics#invite_all_filtered_users', as: "invite_all_filtered_users"
  post 'topics/:id/manage_users/disinvite' => 'topics#disinvite_user', as: "disinvite_user"
  post 'topics/:id/leave_topic' => 'topics#leave_topic', as: "leave_topic"

  root 'topics#index'

end

app/views/layouts/_text_decoration.html.erb
<span onClick="appendLink('<%= id %>')" class="glyphicon glyphicon-link glyphicon-form" title="Link anhängen"></span>
<!--pan onClick="appendBoldText('<%= id %>')" class="glyphicon glyphicon-bold glyphicon-form" title="Fettgeschriebenen Text einfügen"></span>
<span onClick="appendItalicText('<%= id %>')" class="glyphicon glyphicon-italic glyphicon-form" title="Kursiven Text einfügen"></span>
<span onClick="appendColoredText('<%= id %>')" class="glyphicon glyphicon-pencil glyphicon-form" title="Kursiven Text einfügen"></span-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Krautsalat</title>
  <%= stylesheet_link_tag    'application', media: 'screen, projection', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'print', media: 'print', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
	<body>

		<nav class="navbar navbar-default">
			<div class="container">
				<div class="navbar-header">
					<%= link_to "Krautsalat", root_path, class:"navbar-brand"%>
				</div>
				<ul class="nav navbar-nav">
				<% unless user_signed_in? %>
					<li><%= link_to "Registrieren", new_user_registration_path %></li>
				<% end %>
				<% if user_signed_in? %>
					<li><%= link_to "Ausloggen", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Login", new_user_session_path %></li>
				<% end %>
				<% if user_signed_in? && current_user.rights == 2 %>
					<li><%= link_to "Rechte verwalten", rights_path %></li>
				<% end %>
				</ul>
				<% if user_signed_in? && current_user.rights >= 1 %>
					<%= link_to "Neues Thema", new_topic_path, class:"navbar-right navbar-text navbar-link" %>
				<% end %>
			</div>
		</nav>

		<p class="notice"><%= notice %></p>
	    <p class="alert"><%= alert %></p>

	    
			<%= yield %>
	

	</body>
</html>